In [ ]:
import nltk
import pandas as pd
from pprint import pprint
from collections import Counter
import random
import difflib
from wordfreq import zipf_frequency
from nltk.corpus import wordnet as wn

In [2]:
#prendi il primo synset nominale di WordNet associato alla parola "vehicle".
vehicle = wn.synset("vehicle.n.01")

print(vehicle)
print(vehicle.definition())
print()

Synset('vehicle.n.01')
a conveyance that transports people or objects

In [ ]:
#Analisi esplorativa di iponomi di Vehicle nodo 1
for synset in vehicle.hyponyms():
    print(synset.name(), "-", synset.definition())

craft.n.02 - a vehicle designed for navigation in or on water or air or through outer space
skibob.n.01 - a vehicle resembling a bicycle but having skis instead of wheels; the rider wears short skis for balancing
sled.n.01 - a vehicle mounted on runners and pulled by horses or dogs; for transportation over snow
military_vehicle.n.01 - vehicle used by the armed forces
steamroller.n.02 - vehicle equipped with heavy wide smooth rollers for compacting roads and pavements
wheeled_vehicle.n.01 - a vehicle that moves on wheels and usually has a container for transporting things or people
rocket.n.01 - any vehicle self-propelled by a rocket engine
bumper_car.n.01 - a small low-powered electrically powered vehicle driven on a special platform where there are many others to be dodged

In [ ]:
#Analisi esplorativa di iponomi di Vehicle nodo 2
for synset in vehicle.hyponyms():
    print("\n", synset.name(), "-", synset.definition())
    
    for child in synset.hyponyms():
        print("   ->", child.name(), "-", child.definition())

 craft.n.02 - a vehicle designed for navigation in or on water or air or through outer space
   -> hovercraft.n.01 - a craft capable of moving over water or land on a cushion of air created by jet engines
   -> vessel.n.02 - a craft designed for water transportation
   -> spacecraft.n.01 - a craft capable of traveling in outer space; technically, a satellite around the sun
   -> landing_craft.n.01 - naval craft designed for putting ashore troops and equipment
   -> aircraft.n.01 - a vehicle that can fly

 skibob.n.01 - a vehicle resembling a bicycle but having skis instead of wheels; the rider wears short skis for balancing

 sled.n.01 - a vehicle mounted on runners and pulled by horses or dogs; for transportation over snow
   -> pung.n.01 - a one-horse sleigh consisting of a box on runners
   -> luge.n.01 - a racing sled for one or two people
   -> bobsled.n.02 - a long racing sled (for 2 or more people) with a steering mechanism
   -> toboggan.n.01 - a long narrow sled without runners; boards curve upward in front
   -> bobsled.n.01 - formerly two short sleds coupled together
   -> dogsled.n.01 - a sled pulled by dogs

 military_vehicle.n.01 - vehicle used by the armed forces
   -> caisson.n.02 - a two-wheeled military vehicle carrying artillery ammunition
   -> reconnaissance_vehicle.n.01 - fast armored military vehicle with four-wheel drive and open top
   -> tank.n.01 - an enclosed armored military vehicle; has a cannon and moves on caterpillar treads
   -> warship.n.01 - a government ship that is available for waging war
   -> picket.n.04 - a vehicle performing sentinel duty
   -> humvee.n.01 - a high mobility, multipurpose, military vehicle with four-wheel drive
   -> half_track.n.01 - a motor vehicle propelled by half tracks; frequently used by the military
   -> warplane.n.01 - an aircraft designed and used for combat
   -> technical.n.01 - a pickup truck with a gun mounted on it
   -> troop_carrier.n.01 - any land or sea or air vehicle designed to carry troops
   -> personnel_carrier.n.01 - a military vehicle (usually armored) for transporting military personnel and their equipment
   -> weapons_carrier.n.01 - military vehicle that is a light truck designed to carry mortars or machine guns and their crews

 steamroller.n.02 - vehicle equipped with heavy wide smooth rollers for compacting roads and pavements

 wheeled_vehicle.n.01 - a vehicle that moves on wheels and usually has a container for transporting things or people
   -> horse-drawn_vehicle.n.01 - a wheeled vehicle drawn by one or more horses
   -> self-propelled_vehicle.n.01 - a wheeled vehicle that carries in itself a means of propulsion
   -> trailer.n.04 - a wheeled vehicle that can be pulled by a car or truck and is equipped for occupancy
   -> tricycle.n.01 - a vehicle with three wheels that is moved by foot pedals
   -> car.n.02 - a wheeled vehicle adapted to the rails of railroad
   -> handcart.n.01 - wheeled vehicle that can be pushed by a person; may have one or two or four wheels
   -> boneshaker.n.01 - any wheeled vehicle that is dilapidated and uncomfortable
   -> wagon.n.04 - a child's four-wheeled toy cart sometimes used for coasting
   -> welcome_wagon.n.01 - a wheeled vehicle carrying information and gifts from local merchants for new residents in an area
   -> scooter.n.02 - child's two-wheeled vehicle operated by foot
   -> wagon.n.01 - any of various kinds of wheeled vehicles drawn by an animal or a tractor
   -> rolling_stock.n.01 - collection of wheeled vehicles owned by a railroad or motor carrier
   -> unicycle.n.01 - a vehicle with a single wheel that is driven by pedals
   -> skateboard.n.01 - a board with wheels that is ridden in a standing or crouching position and propelled by foot
   -> bicycle.n.01 - a wheeled vehicle that has two wheels and is moved by foot pedals
   -> motor_scooter.n.01 - a wheeled vehicle with small wheels and a low-powered gasoline engine geared to the rear wheel
   -> baby_buggy.n.01 - a small vehicle with four wheels in which a baby or child is pushed around

 rocket.n.01 - any vehicle self-propelled by a rocket engine
   -> missile.n.01 - a rocket carrying a warhead of conventional or nuclear explosives; may be ballistic or directed by remote control
   -> test_rocket.n.01 - a rocket fired for test purposes
   -> multistage_rocket.n.01 - a rocket having two or more rocket engines (each with its own fuel) that are fired in succession and jettisoned when the fuel is exhausted

 bumper_car.n.01 - a small low-powered electrically powered vehicle driven on a special platform where there are many others to be dodged

In [ ]:
#Analisi esplorativa di iponomi di Vehicle nodo 3
for synset in vehicle.hyponyms():
    
    print("\n", synset.name(), "-", synset.definition())

    for child in synset.hyponyms():
        
        print("   ->", child.name(), "-", child.definition())

        for grandchild in child.hyponyms():
            print("      ->", grandchild.name(), "-", grandchild.definition())

 craft.n.02 - a vehicle designed for navigation in or on water or air or through outer space
   -> hovercraft.n.01 - a craft capable of moving over water or land on a cushion of air created by jet engines
   -> vessel.n.02 - a craft designed for water transportation
      -> weather_ship.n.01 - an oceangoing vessel equipped to make meteorological observations
      -> galley.n.01 - a large medieval vessel with a single deck propelled by sails and oars with guns at stern and prow; a complement of 1,000 men; used mainly in the Mediterranean for war and trading
      -> iceboat.n.02 - a sailing vessel with runners and a cross-shaped frame; suitable for traveling over ice
      -> patrol_boat.n.01 - a vessel assigned to patrol an area
      -> ship.n.01 - a vessel that carries passengers or freight
      -> yacht.n.01 - an expensive vessel propelled by sail or power and used for cruising or racing
      -> boat.n.01 - a small vessel for travel on water
      -> shrimper.n.01 - a vessel engaged in shrimping
      -> sailing_vessel.n.01 - a vessel that is powered by the wind; often having several masts
      -> fishing_boat.n.01 - a vessel for fishing; often has a well to keep the catch alive
      -> galley.n.02 - (classical antiquity) a crescent-shaped seagoing vessel propelled by oars
      -> bareboat.n.01 - a vessel (such as a yacht) that can be chartered without a captain or crew or provisions
   -> spacecraft.n.01 - a craft capable of traveling in outer space; technically, a satellite around the sun
      -> space_shuttle.n.01 - a reusable spacecraft with wings for a controlled descent through the Earth's atmosphere
      -> starship.n.01 - a spacecraft designed to carry a crew into interstellar space (especially in science fiction)
      -> lunar_excursion_module.n.01 - a spacecraft that carries astronauts from the command module to the surface of the moon and back
      -> lander.n.02 - a space vehicle that is designed to land on the moon or another planet
      -> space_capsule.n.01 - a spacecraft designed to transport people and support human life in outer space
   -> landing_craft.n.01 - naval craft designed for putting ashore troops and equipment
   -> aircraft.n.01 - a vehicle that can fly
      -> cruise_missile.n.01 - an unmanned aircraft that is a self-contained bomb
      -> heavier-than-air_craft.n.01 - a non-buoyant aircraft that requires a source of power to hold it aloft and to propel it
      -> bogy.n.01 - an unidentified (and possibly enemy) aircraft
      -> lighter-than-air_craft.n.01 - aircraft supported by its own buoyancy
      -> stealth_aircraft.n.01 - an aircraft designed in accordance with technology that makes detection by radar difficult

 skibob.n.01 - a vehicle resembling a bicycle but having skis instead of wheels; the rider wears short skis for balancing

 sled.n.01 - a vehicle mounted on runners and pulled by horses or dogs; for transportation over snow
   -> pung.n.01 - a one-horse sleigh consisting of a box on runners
   -> luge.n.01 - a racing sled for one or two people
   -> bobsled.n.02 - a long racing sled (for 2 or more people) with a steering mechanism
   -> toboggan.n.01 - a long narrow sled without runners; boards curve upward in front
   -> bobsled.n.01 - formerly two short sleds coupled together
   -> dogsled.n.01 - a sled pulled by dogs

 military_vehicle.n.01 - vehicle used by the armed forces
   -> caisson.n.02 - a two-wheeled military vehicle carrying artillery ammunition
   -> reconnaissance_vehicle.n.01 - fast armored military vehicle with four-wheel drive and open top
   -> tank.n.01 - an enclosed armored military vehicle; has a cannon and moves on caterpillar treads
      -> panzer.n.01 - an armored vehicle or tank
   -> warship.n.01 - a government ship that is available for waging war
      -> cruiser.n.02 - a large fast warship; smaller than a battleship and larger than a destroyer
      -> destroyer_escort.n.01 - warship smaller than a destroyer; designed to escort fleets or convoys
      -> aircraft_carrier.n.01 - a large warship that carries planes and has a long flat deck for takeoffs and landings
      -> corvette.n.01 - a highly maneuverable escort warship; smaller than a destroyer
      -> ironclad.n.01 - a wooden warship of the 19th century that is plated with iron or steel armor
      -> guard_ship.n.01 - a warship (at anchor or under way) required to maintain a higher degree of readiness than others in its squadron
      -> man-of-war.n.01 - a warship intended for combat
      -> three-decker.n.03 - a warship carrying guns on three decks
      -> capital_ship.n.01 - a warship of the first rank in size and armament
      -> frigate.n.01 - a medium size square-rigged warship of the 18th and 19th centuries
      -> privateer.n.02 - a privately owned warship commissioned to prey on the commercial shipping or warships of an enemy nation
      -> submersible.n.02 - a warship designed to operate under water
      -> sloop_of_war.n.01 - a sailing or steam warship having cannons on only one deck
      -> surface_ship.n.01 - a warship that operates on the surface of the water
      -> torpedo_boat.n.01 - small high-speed warship designed for torpedo attacks in coastal waters
      -> battleship.n.01 - large and heavily armoured warship
      -> frigate.n.02 - a United States warship larger than a destroyer and smaller than a cruiser
      -> destroyer.n.01 - a small fast lightly armored but heavily armed warship
   -> picket.n.04 - a vehicle performing sentinel duty
      -> picket_ship.n.01 - a ship serving as a picket
      -> picket_boat.n.01 - a boat serving as a picket
   -> humvee.n.01 - a high mobility, multipurpose, military vehicle with four-wheel drive
   -> half_track.n.01 - a motor vehicle propelled by half tracks; frequently used by the military
   -> warplane.n.01 - an aircraft designed and used for combat
      -> reconnaissance_plane.n.01 - a military airplane used to gain information about an enemy
      -> bomber.n.01 - a military aircraft that drops bombs during flight
      -> fighter.n.02 - a high-speed military or naval airplane designed to destroy enemy aircraft in the air
   -> technical.n.01 - a pickup truck with a gun mounted on it
   -> troop_carrier.n.01 - any land or sea or air vehicle designed to carry troops
      -> troopship.n.01 - ship for transporting troops
   -> personnel_carrier.n.01 - a military vehicle (usually armored) for transporting military personnel and their equipment
   -> weapons_carrier.n.01 - military vehicle that is a light truck designed to carry mortars or machine guns and their crews

 steamroller.n.02 - vehicle equipped with heavy wide smooth rollers for compacting roads and pavements

 wheeled_vehicle.n.01 - a vehicle that moves on wheels and usually has a container for transporting things or people
   -> horse-drawn_vehicle.n.01 - a wheeled vehicle drawn by one or more horses
      -> chariot.n.02 - a two-wheeled horse-drawn battle vehicle; used in war and races in ancient Egypt and Greece and Rome
      -> sulky.n.01 - a light two-wheeled vehicle for one person; drawn by one horse
      -> carriage.n.02 - a vehicle with wheels drawn by one or more horses
      -> limber.n.01 - a two-wheeled horse-drawn vehicle used to pull a field gun or caisson
   -> self-propelled_vehicle.n.01 - a wheeled vehicle that carries in itself a means of propulsion
      -> carrier.n.02 - a self-propelled wheeled vehicle designed specifically to carry something
      -> tracked_vehicle.n.01 - a self-propelled vehicle that moves on tracks
      -> reconnaissance_vehicle.n.01 - fast armored military vehicle with four-wheel drive and open top
      -> motor_vehicle.n.01 - a self-propelled wheeled vehicle that does not run on rails
      -> tractor.n.01 - a wheeled vehicle with large wheels; used in farming and other applications
      -> recreational_vehicle.n.01 - a motorized wheeled vehicle used for camping or other recreational activities
      -> forklift.n.01 - a small industrial vehicle with a power operated forked platform in front that can be inserted under loads to lift and move them
      -> streetcar.n.01 - a wheeled vehicle that runs on rails and is propelled by electricity
      -> locomotive.n.01 - a wheeled vehicle consisting of a self-propelled engine that is used to draw trains along railway tracks
      -> personnel_carrier.n.01 - a military vehicle (usually armored) for transporting military personnel and their equipment
      -> armored_vehicle.n.01 - a vehicle that is protected by armor plate
      -> weapons_carrier.n.01 - military vehicle that is a light truck designed to carry mortars or machine guns and their crews
   -> trailer.n.04 - a wheeled vehicle that can be pulled by a car or truck and is equipped for occupancy
      -> mobile_home.n.01 - a large house trailer that can be connected to utilities and can be parked in one place and used as permanent housing
      -> camper_trailer.n.01 - a trailer equipped for occupancy (especially for holiday trips)
   -> tricycle.n.01 - a vehicle with three wheels that is moved by foot pedals
      -> pedicab.n.01 - a tricycle (usually propelled by pedalling); used in the Orient for transporting passengers for hire
   -> car.n.02 - a wheeled vehicle adapted to the rails of railroad
      -> freight_car.n.01 - a railway car that carries freight
      -> slip_coach.n.01 - a railway car at the end of the train; it can be detached without stopping the train
      -> handcar.n.01 - a small railroad car propelled by hand or by a small motor
      -> tender.n.04 - car attached to a locomotive to carry fuel and water
      -> cabin_car.n.01 - a car on a freight train for use of the train crew; usually the last car on the train
      -> mail_car.n.01 - a railway car in which mail is transported and sorted
      -> passenger_car.n.01 - a railcar where passengers ride
      -> guard's_van.n.01 - the car on a train that is occupied by the guard
      -> club_car.n.01 - railroad car having a bar and tables and lounge chairs
      -> van.n.03 - (Great Britain) a closed railroad car that carries baggage or freight
      -> baggage_car.n.01 - a railway car where passengers' bags are carried
   -> handcart.n.01 - wheeled vehicle that can be pushed by a person; may have one or two or four wheels
      -> shopping_cart.n.01 - a handcart that holds groceries or other goods while shopping
      -> hand_truck.n.01 - a handcart that has a frame with two low wheels and a ledge at the bottom and handles at the top; used to move crates or other heavy objects
      -> laundry_cart.n.01 - handcart for moving a load of laundry
      -> barrow.n.03 - a cart for carrying small loads; has handles and one or more wheels
      -> serving_cart.n.01 - a handcart for serving food
      -> applecart.n.02 - a handcart from which apples and other fruit are sold in the street
   -> boneshaker.n.01 - any wheeled vehicle that is dilapidated and uncomfortable
   -> wagon.n.04 - a child's four-wheeled toy cart sometimes used for coasting
   -> welcome_wagon.n.01 - a wheeled vehicle carrying information and gifts from local merchants for new residents in an area
   -> scooter.n.02 - child's two-wheeled vehicle operated by foot
   -> wagon.n.01 - any of various kinds of wheeled vehicles drawn by an animal or a tractor
      -> chuck_wagon.n.01 - a wagon equipped with a cookstove and provisions (for cowboys)
      -> cart.n.01 - a heavy open wagon usually having two wheels and drawn by an animal
      -> covered_wagon.n.01 - a large wagon with broad wheels and an arched canvas top; used by the United States pioneers to cross the prairies in the 19th century
      -> wain.n.03 - large open farm wagon
      -> tramcar.n.01 - a four-wheeled wagon that runs on tracks in a mine
      -> bandwagon.n.02 - a large ornate wagon for carrying a musical band
      -> water_wagon.n.01 - a wagon that carries water (as for troops or work gangs or to sprinkle down dusty dirt roads in the summertime)
      -> lorry.n.01 - a large low horse-drawn wagon without sides
      -> ice_wagon.n.01 - (formerly) a horse-drawn wagon that delivered ice door to door
      -> milk_wagon.n.01 - wagon for delivering milk
   -> rolling_stock.n.01 - collection of wheeled vehicles owned by a railroad or motor carrier
   -> unicycle.n.01 - a vehicle with a single wheel that is driven by pedals
   -> skateboard.n.01 - a board with wheels that is ridden in a standing or crouching position and propelled by foot
   -> bicycle.n.01 - a wheeled vehicle that has two wheels and is moved by foot pedals
      -> velocipede.n.01 - any of several early bicycles with pedals on the front wheel
      -> push-bike.n.01 - a bicycle that must be pedaled
      -> ordinary.n.04 - an early bicycle with a very large front wheel and small back wheel
      -> bicycle-built-for-two.n.01 - a bicycle with two sets of pedals and two seats
      -> safety_bicycle.n.01 - bicycle that has two wheels of equal size; pedals are connected to the rear wheel by a multiplying gear
      -> mountain_bike.n.01 - a bicycle with a sturdy frame and fat tires; originally designed for riding in mountainous country
   -> motor_scooter.n.01 - a wheeled vehicle with small wheels and a low-powered gasoline engine geared to the rear wheel
   -> baby_buggy.n.01 - a small vehicle with four wheels in which a baby or child is pushed around
      -> bassinet.n.02 - a perambulator that resembles a bassinet

 rocket.n.01 - any vehicle self-propelled by a rocket engine
   -> missile.n.01 - a rocket carrying a warhead of conventional or nuclear explosives; may be ballistic or directed by remote control
      -> sidewinder.n.02 - air-to-air missile with infrared homing device
      -> ballistic_missile.n.01 - a missile that is guided in the first part of its flight but falls freely as it approaches target
      -> heat-seeking_missile.n.01 - a missile with a guidance system that directs it toward targets emitting infrared radiation (as the emissions of a jet engine)
      -> air-to-air_missile.n.01 - a missile designed to be launched from one airplane at another
      -> guided_missile.n.01 - a rocket-propelled missile whose path can be controlled during flight either by radio signals or by internal homing devices
      -> air-to-ground_missile.n.01 - a missile designed to be launched from an airplane at a target on the ground
   -> test_rocket.n.01 - a rocket fired for test purposes
      -> sounding_rocket.n.01 - a research rocket used to obtain information about the atmosphere at various altitudes
   -> multistage_rocket.n.01 - a rocket having two or more rocket engines (each with its own fuel) that are fired in succession and jettisoned when the fuel is exhausted

 bumper_car.n.01 - a small low-powered electrically powered vehicle driven on a special platform where there are many others to be dodged

In [ ]:
#funzione per creare lista di iponomi fino a profondità 3 da vehicle
tree = vehicle.tree(lambda s: s.hyponyms(), depth=3)

print(tree)

[Synset('vehicle.n.01'), [Synset('craft.n.02'), [Synset('hovercraft.n.01')], [Synset('vessel.n.02'), [Synset('weather_ship.n.01')], [Synset('galley.n.01')], [Synset('iceboat.n.02')], [Synset('patrol_boat.n.01')], [Synset('ship.n.01')], [Synset('yacht.n.01')], [Synset('boat.n.01')], [Synset('shrimper.n.01')], [Synset('sailing_vessel.n.01')], [Synset('fishing_boat.n.01')], [Synset('galley.n.02')], [Synset('bareboat.n.01')]], [Synset('spacecraft.n.01'), [Synset('space_shuttle.n.01')], [Synset('starship.n.01')], [Synset('lunar_excursion_module.n.01')], [Synset('lander.n.02')], [Synset('space_capsule.n.01')]], [Synset('landing_craft.n.01')], [Synset('aircraft.n.01'), [Synset('cruise_missile.n.01')], [Synset('heavier-than-air_craft.n.01')], [Synset('bogy.n.01')], [Synset('lighter-than-air_craft.n.01')], [Synset('stealth_aircraft.n.01')]]], [Synset('skibob.n.01')], [Synset('sled.n.01'), [Synset('pung.n.01')], [Synset('luge.n.01')], [Synset('bobsled.n.02')], [Synset('toboggan.n.01')], [Synset('bobsled.n.01')], [Synset('dogsled.n.01')]], [Synset('military_vehicle.n.01'), [Synset('caisson.n.02')], [Synset('reconnaissance_vehicle.n.01')], [Synset('tank.n.01'), [Synset('panzer.n.01')]], [Synset('warship.n.01'), [Synset('cruiser.n.02')], [Synset('destroyer_escort.n.01')], [Synset('aircraft_carrier.n.01')], [Synset('corvette.n.01')], [Synset('ironclad.n.01')], [Synset('guard_ship.n.01')], [Synset('man-of-war.n.01')], [Synset('three-decker.n.03')], [Synset('capital_ship.n.01')], [Synset('frigate.n.01')], [Synset('privateer.n.02')], [Synset('submersible.n.02')], [Synset('sloop_of_war.n.01')], [Synset('surface_ship.n.01')], [Synset('torpedo_boat.n.01')], [Synset('battleship.n.01')], [Synset('frigate.n.02')], [Synset('destroyer.n.01')]], [Synset('picket.n.04'), [Synset('picket_ship.n.01')], [Synset('picket_boat.n.01')]], [Synset('humvee.n.01')], [Synset('half_track.n.01')], [Synset('warplane.n.01'), [Synset('reconnaissance_plane.n.01')], [Synset('bomber.n.01')], [Synset('fighter.n.02')]], [Synset('technical.n.01')], [Synset('troop_carrier.n.01'), [Synset('troopship.n.01')]], [Synset('personnel_carrier.n.01')], [Synset('weapons_carrier.n.01')]], [Synset('steamroller.n.02')], [Synset('wheeled_vehicle.n.01'), [Synset('horse-drawn_vehicle.n.01'), [Synset('chariot.n.02')], [Synset('sulky.n.01')], [Synset('carriage.n.02')], [Synset('limber.n.01')]], [Synset('self-propelled_vehicle.n.01'), [Synset('carrier.n.02')], [Synset('tracked_vehicle.n.01')], [Synset('reconnaissance_vehicle.n.01')], [Synset('motor_vehicle.n.01')], [Synset('tractor.n.01')], [Synset('recreational_vehicle.n.01')], [Synset('forklift.n.01')], [Synset('streetcar.n.01')], [Synset('locomotive.n.01')], [Synset('personnel_carrier.n.01')], [Synset('armored_vehicle.n.01')], [Synset('weapons_carrier.n.01')]], [Synset('trailer.n.04'), [Synset('mobile_home.n.01')], [Synset('camper_trailer.n.01')]], [Synset('tricycle.n.01'), [Synset('pedicab.n.01')]], [Synset('car.n.02'), [Synset('freight_car.n.01')], [Synset('slip_coach.n.01')], [Synset('handcar.n.01')], [Synset('tender.n.04')], [Synset('cabin_car.n.01')], [Synset('mail_car.n.01')], [Synset('passenger_car.n.01')], [Synset('guard's_van.n.01')], [Synset('club_car.n.01')], [Synset('van.n.03')], [Synset('baggage_car.n.01')]], [Synset('handcart.n.01'), [Synset('shopping_cart.n.01')], [Synset('hand_truck.n.01')], [Synset('laundry_cart.n.01')], [Synset('barrow.n.03')], [Synset('serving_cart.n.01')], [Synset('applecart.n.02')]], [Synset('boneshaker.n.01')], [Synset('wagon.n.04')], [Synset('welcome_wagon.n.01')], [Synset('scooter.n.02')], [Synset('wagon.n.01'), [Synset('chuck_wagon.n.01')], [Synset('cart.n.01')], [Synset('covered_wagon.n.01')], [Synset('wain.n.03')], [Synset('tramcar.n.01')], [Synset('bandwagon.n.02')], [Synset('water_wagon.n.01')], [Synset('lorry.n.01')], [Synset('ice_wagon.n.01')], [Synset('milk_wagon.n.01')]], [Synset('rolling_stock.n.01')], [Synset('unicycle.n.01')], [Synset('skateboard.n.01')], [Synset('bicycle.n.01'), [Synset('velocipede.n.01')], [Synset('push-bike.n.01')], [Synset('ordinary.n.04')], [Synset('bicycle-built-for-two.n.01')], [Synset('safety_bicycle.n.01')], [Synset('mountain_bike.n.01')]], [Synset('motor_scooter.n.01')], [Synset('baby_buggy.n.01'), [Synset('bassinet.n.02')]]], [Synset('rocket.n.01'), [Synset('missile.n.01'), [Synset('sidewinder.n.02')], [Synset('ballistic_missile.n.01')], [Synset('heat-seeking_missile.n.01')], [Synset('air-to-air_missile.n.01')], [Synset('guided_missile.n.01')], [Synset('air-to-ground_missile.n.01')]], [Synset('test_rocket.n.01'), [Synset('sounding_rocket.n.01')]], [Synset('multistage_rocket.n.01')]], [Synset('bumper_car.n.01')]]

In [9]:
pprint(tree)

[Synset('vehicle.n.01'),
 [Synset('craft.n.02'),
  [Synset('hovercraft.n.01')],
  [Synset('vessel.n.02'),
   [Synset('weather_ship.n.01')],
   [Synset('galley.n.01')],
   [Synset('iceboat.n.02')],
   [Synset('patrol_boat.n.01')],
   [Synset('ship.n.01')],
   [Synset('yacht.n.01')],
   [Synset('boat.n.01')],
   [Synset('shrimper.n.01')],
   [Synset('sailing_vessel.n.01')],
   [Synset('fishing_boat.n.01')],
   [Synset('galley.n.02')],
   [Synset('bareboat.n.01')]],
  [Synset('spacecraft.n.01'),
   [Synset('space_shuttle.n.01')],
   [Synset('starship.n.01')],
   [Synset('lunar_excursion_module.n.01')],
   [Synset('lander.n.02')],
   [Synset('space_capsule.n.01')]],
  [Synset('landing_craft.n.01')],
  [Synset('aircraft.n.01'),
   [Synset('cruise_missile.n.01')],
   [Synset('heavier-than-air_craft.n.01')],
   [Synset('bogy.n.01')],
   [Synset('lighter-than-air_craft.n.01')],
   [Synset('stealth_aircraft.n.01')]]],
 [Synset('skibob.n.01')],
 [Synset('sled.n.01'),
  [Synset('pung.n.01')],
  [Synset('luge.n.01')],
  [Synset('bobsled.n.02')],
  [Synset('toboggan.n.01')],
  [Synset('bobsled.n.01')],
  [Synset('dogsled.n.01')]],
 [Synset('military_vehicle.n.01'),
  [Synset('caisson.n.02')],
  [Synset('reconnaissance_vehicle.n.01')],
  [Synset('tank.n.01'), [Synset('panzer.n.01')]],
  [Synset('warship.n.01'),
   [Synset('cruiser.n.02')],
   [Synset('destroyer_escort.n.01')],
   [Synset('aircraft_carrier.n.01')],
   [Synset('corvette.n.01')],
   [Synset('ironclad.n.01')],
   [Synset('guard_ship.n.01')],
   [Synset('man-of-war.n.01')],
   [Synset('three-decker.n.03')],
   [Synset('capital_ship.n.01')],
   [Synset('frigate.n.01')],
   [Synset('privateer.n.02')],
   [Synset('submersible.n.02')],
   [Synset('sloop_of_war.n.01')],
   [Synset('surface_ship.n.01')],
   [Synset('torpedo_boat.n.01')],
   [Synset('battleship.n.01')],
   [Synset('frigate.n.02')],
   [Synset('destroyer.n.01')]],
  [Synset('picket.n.04'),
   [Synset('picket_ship.n.01')],
   [Synset('picket_boat.n.01')]],
  [Synset('humvee.n.01')],
  [Synset('half_track.n.01')],
  [Synset('warplane.n.01'),
   [Synset('reconnaissance_plane.n.01')],
   [Synset('bomber.n.01')],
   [Synset('fighter.n.02')]],
  [Synset('technical.n.01')],
  [Synset('troop_carrier.n.01'), [Synset('troopship.n.01')]],
  [Synset('personnel_carrier.n.01')],
  [Synset('weapons_carrier.n.01')]],
 [Synset('steamroller.n.02')],
 [Synset('wheeled_vehicle.n.01'),
  [Synset('horse-drawn_vehicle.n.01'),
   [Synset('chariot.n.02')],
   [Synset('sulky.n.01')],
   [Synset('carriage.n.02')],
   [Synset('limber.n.01')]],
  [Synset('self-propelled_vehicle.n.01'),
   [Synset('carrier.n.02')],
   [Synset('tracked_vehicle.n.01')],
   [Synset('reconnaissance_vehicle.n.01')],
   [Synset('motor_vehicle.n.01')],
   [Synset('tractor.n.01')],
   [Synset('recreational_vehicle.n.01')],
   [Synset('forklift.n.01')],
   [Synset('streetcar.n.01')],
   [Synset('locomotive.n.01')],
   [Synset('personnel_carrier.n.01')],
   [Synset('armored_vehicle.n.01')],
   [Synset('weapons_carrier.n.01')]],
  [Synset('trailer.n.04'),
   [Synset('mobile_home.n.01')],
   [Synset('camper_trailer.n.01')]],
  [Synset('tricycle.n.01'), [Synset('pedicab.n.01')]],
  [Synset('car.n.02'),
   [Synset('freight_car.n.01')],
   [Synset('slip_coach.n.01')],
   [Synset('handcar.n.01')],
   [Synset('tender.n.04')],
   [Synset('cabin_car.n.01')],
   [Synset('mail_car.n.01')],
   [Synset('passenger_car.n.01')],
   [Synset('guard's_van.n.01')],
   [Synset('club_car.n.01')],
   [Synset('van.n.03')],
   [Synset('baggage_car.n.01')]],
  [Synset('handcart.n.01'),
   [Synset('shopping_cart.n.01')],
   [Synset('hand_truck.n.01')],
   [Synset('laundry_cart.n.01')],
   [Synset('barrow.n.03')],
   [Synset('serving_cart.n.01')],
   [Synset('applecart.n.02')]],
  [Synset('boneshaker.n.01')],
  [Synset('wagon.n.04')],
  [Synset('welcome_wagon.n.01')],
  [Synset('scooter.n.02')],
  [Synset('wagon.n.01'),
   [Synset('chuck_wagon.n.01')],
   [Synset('cart.n.01')],
   [Synset('covered_wagon.n.01')],
   [Synset('wain.n.03')],
   [Synset('tramcar.n.01')],
   [Synset('bandwagon.n.02')],
   [Synset('water_wagon.n.01')],
   [Synset('lorry.n.01')],
   [Synset('ice_wagon.n.01')],
   [Synset('milk_wagon.n.01')]],
  [Synset('rolling_stock.n.01')],
  [Synset('unicycle.n.01')],
  [Synset('skateboard.n.01')],
  [Synset('bicycle.n.01'),
   [Synset('velocipede.n.01')],
   [Synset('push-bike.n.01')],
   [Synset('ordinary.n.04')],
   [Synset('bicycle-built-for-two.n.01')],
   [Synset('safety_bicycle.n.01')],
   [Synset('mountain_bike.n.01')]],
  [Synset('motor_scooter.n.01')],
  [Synset('baby_buggy.n.01'), [Synset('bassinet.n.02')]]],
 [Synset('rocket.n.01'),
  [Synset('missile.n.01'),
   [Synset('sidewinder.n.02')],
   [Synset('ballistic_missile.n.01')],
   [Synset('heat-seeking_missile.n.01')],
   [Synset('air-to-air_missile.n.01')],
   [Synset('guided_missile.n.01')],
   [Synset('air-to-ground_missile.n.01')]],
  [Synset('test_rocket.n.01'), [Synset('sounding_rocket.n.01')]],
  [Synset('multistage_rocket.n.01')]],
 [Synset('bumper_car.n.01')]]

In [ ]:
def get_nodes(tree):
    #in input si manda la struttura tree di synset 
    #restituisce una lista di nodi con ilemmi corrispondenti ai synset ottenuti
    nodes = []
    node = tree[0]
    nodes.append(node)

    for child in tree[1:]:
        nodes.extend(get_nodes(child))

    return nodes
nodes = get_nodes(tree)

print(nodes)

[Synset('vehicle.n.01'), Synset('craft.n.02'), Synset('hovercraft.n.01'), Synset('vessel.n.02'), Synset('weather_ship.n.01'), Synset('galley.n.01'), Synset('iceboat.n.02'), Synset('patrol_boat.n.01'), Synset('ship.n.01'), Synset('yacht.n.01'), Synset('boat.n.01'), Synset('shrimper.n.01'), Synset('sailing_vessel.n.01'), Synset('fishing_boat.n.01'), Synset('galley.n.02'), Synset('bareboat.n.01'), Synset('spacecraft.n.01'), Synset('space_shuttle.n.01'), Synset('starship.n.01'), Synset('lunar_excursion_module.n.01'), Synset('lander.n.02'), Synset('space_capsule.n.01'), Synset('landing_craft.n.01'), Synset('aircraft.n.01'), Synset('cruise_missile.n.01'), Synset('heavier-than-air_craft.n.01'), Synset('bogy.n.01'), Synset('lighter-than-air_craft.n.01'), Synset('stealth_aircraft.n.01'), Synset('skibob.n.01'), Synset('sled.n.01'), Synset('pung.n.01'), Synset('luge.n.01'), Synset('bobsled.n.02'), Synset('toboggan.n.01'), Synset('bobsled.n.01'), Synset('dogsled.n.01'), Synset('military_vehicle.n.01'), Synset('caisson.n.02'), Synset('reconnaissance_vehicle.n.01'), Synset('tank.n.01'), Synset('panzer.n.01'), Synset('warship.n.01'), Synset('cruiser.n.02'), Synset('destroyer_escort.n.01'), Synset('aircraft_carrier.n.01'), Synset('corvette.n.01'), Synset('ironclad.n.01'), Synset('guard_ship.n.01'), Synset('man-of-war.n.01'), Synset('three-decker.n.03'), Synset('capital_ship.n.01'), Synset('frigate.n.01'), Synset('privateer.n.02'), Synset('submersible.n.02'), Synset('sloop_of_war.n.01'), Synset('surface_ship.n.01'), Synset('torpedo_boat.n.01'), Synset('battleship.n.01'), Synset('frigate.n.02'), Synset('destroyer.n.01'), Synset('picket.n.04'), Synset('picket_ship.n.01'), Synset('picket_boat.n.01'), Synset('humvee.n.01'), Synset('half_track.n.01'), Synset('warplane.n.01'), Synset('reconnaissance_plane.n.01'), Synset('bomber.n.01'), Synset('fighter.n.02'), Synset('technical.n.01'), Synset('troop_carrier.n.01'), Synset('troopship.n.01'), Synset('personnel_carrier.n.01'), Synset('weapons_carrier.n.01'), Synset('steamroller.n.02'), Synset('wheeled_vehicle.n.01'), Synset('horse-drawn_vehicle.n.01'), Synset('chariot.n.02'), Synset('sulky.n.01'), Synset('carriage.n.02'), Synset('limber.n.01'), Synset('self-propelled_vehicle.n.01'), Synset('carrier.n.02'), Synset('tracked_vehicle.n.01'), Synset('reconnaissance_vehicle.n.01'), Synset('motor_vehicle.n.01'), Synset('tractor.n.01'), Synset('recreational_vehicle.n.01'), Synset('forklift.n.01'), Synset('streetcar.n.01'), Synset('locomotive.n.01'), Synset('personnel_carrier.n.01'), Synset('armored_vehicle.n.01'), Synset('weapons_carrier.n.01'), Synset('trailer.n.04'), Synset('mobile_home.n.01'), Synset('camper_trailer.n.01'), Synset('tricycle.n.01'), Synset('pedicab.n.01'), Synset('car.n.02'), Synset('freight_car.n.01'), Synset('slip_coach.n.01'), Synset('handcar.n.01'), Synset('tender.n.04'), Synset('cabin_car.n.01'), Synset('mail_car.n.01'), Synset('passenger_car.n.01'), Synset('guard's_van.n.01'), Synset('club_car.n.01'), Synset('van.n.03'), Synset('baggage_car.n.01'), Synset('handcart.n.01'), Synset('shopping_cart.n.01'), Synset('hand_truck.n.01'), Synset('laundry_cart.n.01'), Synset('barrow.n.03'), Synset('serving_cart.n.01'), Synset('applecart.n.02'), Synset('boneshaker.n.01'), Synset('wagon.n.04'), Synset('welcome_wagon.n.01'), Synset('scooter.n.02'), Synset('wagon.n.01'), Synset('chuck_wagon.n.01'), Synset('cart.n.01'), Synset('covered_wagon.n.01'), Synset('wain.n.03'), Synset('tramcar.n.01'), Synset('bandwagon.n.02'), Synset('water_wagon.n.01'), Synset('lorry.n.01'), Synset('ice_wagon.n.01'), Synset('milk_wagon.n.01'), Synset('rolling_stock.n.01'), Synset('unicycle.n.01'), Synset('skateboard.n.01'), Synset('bicycle.n.01'), Synset('velocipede.n.01'), Synset('push-bike.n.01'), Synset('ordinary.n.04'), Synset('bicycle-built-for-two.n.01'), Synset('safety_bicycle.n.01'), Synset('mountain_bike.n.01'), Synset('motor_scooter.n.01'), Synset('baby_buggy.n.01'), Synset('bassinet.n.02'), Synset('rocket.n.01'), Synset('missile.n.01'), Synset('sidewinder.n.02'), Synset('ballistic_missile.n.01'), Synset('heat-seeking_missile.n.01'), Synset('air-to-air_missile.n.01'), Synset('guided_missile.n.01'), Synset('air-to-ground_missile.n.01'), Synset('test_rocket.n.01'), Synset('sounding_rocket.n.01'), Synset('multistage_rocket.n.01'), Synset('bumper_car.n.01')]

In [13]:
print(vehicle.shortest_path_distance(wn.synset("craft.n.02")))
print(vehicle.shortest_path_distance(wn.synset("vessel.n.02")))
print(vehicle.shortest_path_distance(wn.synset("ship.n.01")))

1
2
3

In [14]:
for synset in nodes[:10]:
    print(synset.name(), "->", synset.lemmas()[0].name())

vehicle.n.01 -> vehicle
craft.n.02 -> craft
hovercraft.n.01 -> hovercraft
vessel.n.02 -> vessel
weather_ship.n.01 -> weather_ship
galley.n.01 -> galley
iceboat.n.02 -> iceboat
patrol_boat.n.01 -> patrol_boat
ship.n.01 -> ship
yacht.n.01 -> yacht

In [ ]:
#si crea lista di lemmi: ogni lemma in lista è nella stessa posizione del corrispettivo synset in nodes
words = [synset.lemmas()[0].name() for synset in nodes]

print(words)

['vehicle', 'craft', 'hovercraft', 'vessel', 'weather_ship', 'galley', 'iceboat', 'patrol_boat', 'ship', 'yacht', 'boat', 'shrimper', 'sailing_vessel', 'fishing_boat', 'galley', 'bareboat', 'spacecraft', 'space_shuttle', 'starship', 'lunar_excursion_module', 'lander', 'space_capsule', 'landing_craft', 'aircraft', 'cruise_missile', 'heavier-than-air_craft', 'bogy', 'lighter-than-air_craft', 'stealth_aircraft', 'skibob', 'sled', 'pung', 'luge', 'bobsled', 'toboggan', 'bobsled', 'dogsled', 'military_vehicle', 'caisson', 'reconnaissance_vehicle', 'tank', 'panzer', 'warship', 'cruiser', 'destroyer_escort', 'aircraft_carrier', 'corvette', 'ironclad', 'guard_ship', 'man-of-war', 'three-decker', 'capital_ship', 'frigate', 'privateer', 'submersible', 'sloop_of_war', 'surface_ship', 'torpedo_boat', 'battleship', 'frigate', 'destroyer', 'picket', 'picket_ship', 'picket_boat', 'Humvee', 'half_track', 'warplane', 'reconnaissance_plane', 'bomber', 'fighter', 'technical', 'troop_carrier', 'troopship', 'personnel_carrier', 'weapons_carrier', 'steamroller', 'wheeled_vehicle', 'horse-drawn_vehicle', 'chariot', 'sulky', 'carriage', 'limber', 'self-propelled_vehicle', 'carrier', 'tracked_vehicle', 'reconnaissance_vehicle', 'motor_vehicle', 'tractor', 'recreational_vehicle', 'forklift', 'streetcar', 'locomotive', 'personnel_carrier', 'armored_vehicle', 'weapons_carrier', 'trailer', 'mobile_home', 'camper_trailer', 'tricycle', 'pedicab', 'car', 'freight_car', 'slip_coach', 'handcar', 'tender', 'cabin_car', 'mail_car', 'passenger_car', "guard's_van", 'club_car', 'van', 'baggage_car', 'handcart', 'shopping_cart', 'hand_truck', 'laundry_cart', 'barrow', 'serving_cart', 'applecart', 'boneshaker', 'wagon', 'welcome_wagon', 'scooter', 'wagon', 'chuck_wagon', 'cart', 'covered_wagon', 'wain', 'tramcar', 'bandwagon', 'water_wagon', 'lorry', 'ice_wagon', 'milk_wagon', 'rolling_stock', 'unicycle', 'skateboard', 'bicycle', 'velocipede', 'push-bike', 'ordinary', 'bicycle-built-for-two', 'safety_bicycle', 'mountain_bike', 'motor_scooter', 'baby_buggy', 'bassinet', 'rocket', 'missile', 'sidewinder', 'ballistic_missile', 'heat-seeking_missile', 'air-to-air_missile', 'guided_missile', 'air-to-ground_missile', 'test_rocket', 'sounding_rocket', 'multistage_rocket', 'bumper_car']

In [ ]:
#nodi filtrati lunghezza parole > 3, tolgo parole composte, parole arcaiche eliminate
filtered_nodes = []
seen_words = set()

for synset in nodes:
    word = synset.lemmas()[0].name()

    if (
        word.isalpha()
        and len(word) >= 3
        and zipf_frequency(word, "en") >= 2.5
    ):
        filtered_nodes.append(synset)
        seen_words.add(word.lower())

In [27]:
print("Nodi originali:", len(nodes))
print("Nodi filtrati:", len(filtered_nodes))

Nodi originali: 159
Nodi filtrati: 55

In [28]:
for synset in filtered_nodes:
    print(synset.name(), "->", synset.lemmas()[0].name())

vehicle.n.01 -> vehicle
craft.n.02 -> craft
hovercraft.n.01 -> hovercraft
vessel.n.02 -> vessel
galley.n.01 -> galley
ship.n.01 -> ship
yacht.n.01 -> yacht
boat.n.01 -> boat
galley.n.02 -> galley
spacecraft.n.01 -> spacecraft
starship.n.01 -> starship
lander.n.02 -> lander
aircraft.n.01 -> aircraft
sled.n.01 -> sled
luge.n.01 -> luge
tank.n.01 -> tank
panzer.n.01 -> panzer
warship.n.01 -> warship
cruiser.n.02 -> cruiser
corvette.n.01 -> corvette
ironclad.n.01 -> ironclad
frigate.n.01 -> frigate
privateer.n.02 -> privateer
submersible.n.02 -> submersible
battleship.n.01 -> battleship
frigate.n.02 -> frigate
destroyer.n.01 -> destroyer
picket.n.04 -> picket
bomber.n.01 -> bomber
fighter.n.02 -> fighter
technical.n.01 -> technical
chariot.n.02 -> chariot
carriage.n.02 -> carriage
carrier.n.02 -> carrier
tractor.n.01 -> tractor
forklift.n.01 -> forklift
streetcar.n.01 -> streetcar
locomotive.n.01 -> locomotive
trailer.n.04 -> trailer
tricycle.n.01 -> tricycle
car.n.02 -> car
tender.n.04 -> tender
van.n.03 -> van
barrow.n.03 -> barrow
wagon.n.04 -> wagon
scooter.n.02 -> scooter
wagon.n.01 -> wagon
cart.n.01 -> cart
bandwagon.n.02 -> bandwagon
lorry.n.01 -> lorry
skateboard.n.01 -> skateboard
bicycle.n.01 -> bicycle
ordinary.n.04 -> ordinary
rocket.n.01 -> rocket
missile.n.01 -> missile

In [ ]:
#Altro filtro da applicare: polisemia: se compare una parola associata a due synset diversi nell'albero.
#prima controlliamo nell'insieme dei nodi non filtrati
counts = Counter(words) 
duplicates = {word: count for word, count in counts.items() if count > 1} 
print(duplicates)

{'galley': 2, 'bobsled': 2, 'reconnaissance_vehicle': 2, 'frigate': 2, 'personnel_carrier': 2, 'weapons_carrier': 2, 'wagon': 2}

In [ ]:
#adesso controlliamo nei nodi filtreti, si sono già ridotte
for synset in filtered_nodes:
    word = synset.lemmas()[0].name()

    if word in duplicates:
        print(synset.name(), "->", word)

galley.n.01 -> galley
galley.n.02 -> galley
frigate.n.01 -> frigate
frigate.n.02 -> frigate
wagon.n.04 -> wagon
wagon.n.01 -> wagon

In [ ]:
#  contiamo quanti lemmi uguali ci sono che appartengono a synset diversi --> li filitriamo mantenendo i lemmi contati una sola volta
counts = Counter(
    synset.lemmas()[0].name()
    for synset in filtered_nodes
)

filtered_nodes_unique = [
    synset
    for synset in filtered_nodes
    if counts[synset.lemmas()[0].name()] == 1
]

print("Nodi prima:", len(filtered_nodes))
print("Nodi dopo:", len(filtered_nodes_unique))

Nodi prima: 55
Nodi dopo: 49

In [38]:
#creiamo lista di liste contenenti lemma 1, lemma 2, e la distanza tassonomica dei corrispettivi synset
pairs = []

for i in range(len(filtered_nodes_unique)):
    for j in range(i + 1, len(filtered_nodes_unique)):

        synset1 = filtered_nodes_unique[i]
        synset2 = filtered_nodes_unique[j]

        distance = synset1.shortest_path_distance(synset2)

        if distance is not None:
            word1 = synset1.lemmas()[0].name()
            word2 = synset2.lemmas()[0].name()

            pairs.append((word1, word2, distance))

In [42]:
synset1 = nodes[0]
synset2 = nodes[1]

word1 = words[0]
word2 = words[1]

distance = synset1.shortest_path_distance(synset2)

print(word1, "-", word2, "->", distance)

vehicle - craft -> 1

In [ ]:
#creiamo lista di liste contenenti memma 1, lemma 2, e la distanza tassonomica dei corrispettivi synset 
pairs = []

for i in range(len(nodes)):
    for j in range(i + 1, len(nodes)):
        
        synset1 = nodes[i]
        synset2 = nodes[j]
        
        word1 = words[i]
        word2 = words[j]
        
        distance = synset1.shortest_path_distance(synset2)
        
        pairs.append([word1, word2, distance])

In [39]:
df = pd.DataFrame(
    pairs,
    columns=["word1", "word2", "taxonomic_distance"]
)

df

         word1       word2  taxonomic_distance
0      vehicle       craft                   1
1      vehicle  hovercraft                   2
2      vehicle      vessel                   2
3      vehicle        ship                   3
4      vehicle       yacht                   3
...        ...         ...                 ...
1171   bicycle      rocket                   3
1172   bicycle     missile                   4
1173  ordinary      rocket                   4
1174  ordinary     missile                   5
1175    rocket     missile                   1

[1176 rows x 3 columns]

In [40]:
df.head(20)

      word1        word2  taxonomic_distance
0   vehicle        craft                   1
1   vehicle   hovercraft                   2
2   vehicle       vessel                   2
3   vehicle         ship                   3
4   vehicle        yacht                   3
5   vehicle         boat                   3
6   vehicle   spacecraft                   2
7   vehicle     starship                   3
8   vehicle       lander                   3
9   vehicle     aircraft                   2
10  vehicle         sled                   1
11  vehicle         luge                   2
12  vehicle         tank                   2
13  vehicle       panzer                   3
14  vehicle      warship                   2
15  vehicle      cruiser                   3
16  vehicle     corvette                   3
17  vehicle     ironclad                   3
18  vehicle    privateer                   3
19  vehicle  submersible                   3

In [41]:
df["taxonomic_distance"].value_counts().sort_index()

taxonomic_distance
1     26
2    100
3    215
4    298
5    303
6    234
Name: count, dtype: int64

In [ ]:
#eliminare ripetizioni di parole
df = df[df["taxonomic_distance"] > 0]

In [22]:
df["taxonomic_distance"].value_counts().sort_index()

taxonomic_distance
1     170
2     964
3    1850
4    3182
5    3075
6    3317
Name: count, dtype: int64

In [ ]:
#vogliamo creare un albero più piccolo per la nostra analisi
#calcoliamo quanti iponomi producono gli iponomi di vehicles
branches = vehicle.hyponyms()

for branch in branches:
    print(branch.name(), "->", len(branch.hyponyms()), "figli")

craft.n.02 -> 5 figli
skibob.n.01 -> 0 figli
sled.n.01 -> 6 figli
military_vehicle.n.01 -> 12 figli
steamroller.n.02 -> 0 figli
wheeled_vehicle.n.01 -> 17 figli
rocket.n.01 -> 3 figli
bumper_car.n.01 -> 0 figli

In [ ]:
#controlliamo quanti iponomi producono gli iponomi di vehicles ma il tutto per la nostra lista filtrata
#in pratica creiamo una lista contenente per ogni branca, la radice stessa più tutti gli iponomi conservati dopo i filtri
for branch in vehicle.hyponyms():
    nodes_in_branch = [
        node for node in filtered_nodes_unique
        if node == branch or branch in node.hypernym_paths()[0] #in pratica teniamo se la branca è l'iperonimo più vicino del nodo in questione
    ]

    print(branch.name(), "->", len(nodes_in_branch), "nodi")

craft.n.02 -> 12 nodi
skibob.n.01 -> 0 nodi
sled.n.01 -> 2 nodi
military_vehicle.n.01 -> 12 nodi
steamroller.n.02 -> 0 nodi
wheeled_vehicle.n.01 -> 20 nodi
rocket.n.01 -> 2 nodi
bumper_car.n.01 -> 0 nodi